const Data = [
    {img:"https://th.bing.com/th/id/R.fae30c371fdf03c8270b275fb83e6a2c?rik=HcjPRtk2qWUGyQ&pid=ImgRaw&r=0", title: "Pack libros Harry Potter", precio: "$17.000", description:'Incluye "La piedra filosofal", "La cámara secreta", "El pricionero de Azcaban", "El cáliz de fuego", "La orden del Fénix", "El misterio del príncipe" y "Las reliquias de la muerte"'},
    {img:"https://th.bing.com/th/id/OIP.pSL55k3_2sp2R_mSSmdCbgHaHa?pid=ImgDet&rs=1", title:"Varita Harry Potter", precio:"$5.000", description:'Varita Original de Ollivanders. La varita de Harry Potter mide veintiocho centímetros, y está hecha de acebo, con una pluma de fénix en su centro.'},
    {img:"https://cuernavilla.com/12688/bufanda-ravenclaw-edicion-deluxe-harry-potter.jpg", title:"Bufanda de Ravenclaw", precio:"$4.000", description:'Bufanda de la casa Ravenclaw Original, con los colores azul y brince que caracteriza la casa. Empaque de Harri Potter Original, con etiqueta y escudo del aguila de Ravenclaw.'},
    {img:"https://www.funkotienda.com/wp-content/uploads/2018/04/funko-pop-harry-potter-albus-dumbledore.jpg", title:"Funko Dumbledore", precio:"$8.850", description:'Figura coleccionable Funko Pop de Albus Dumbledore de la película "Harry Potter y la orden del fénix. Caja original. 10cm de altura"'},
    {img:"https://i.pinimg.com/originals/a3/b9/9f/a3b99fdedfcc2fbcf5b18b6acc165797.jpg", title:"Grageas de todos los sabores", precio:"$1.600", description:"Dulces mágicos de todos los sabores. Incluye: banana, huevo podrido, limón, vomito y más."},
    {img:"https://media.entertainmentearth.com/assets/images/93d5a514ef9e44f09add18e7595fcc5dlg.jpg", title:"Sombrero seleccionador", precio:"$24.800", description:"Juguete interactivo del Sombrero seleccionador con voz incluida.Se coloca en la cabeza y mueve su boca para anunciar a qué casa de Hogwarts perteneces."},
    {img:"https://www.for-sale.co.uk/sh-img/91rOTxaOA3L._SL1500__chocolate%2Bfrog.jpg", title:"Rana de chocolate", precio:"$1.600", description:"Tras ranas de chocolate má una figura coleccionable con movimiento de los personajes de Harry Potter. No esperarás que se quede ahí todo el tiempo ¿o sí?"},
    {img:"https://s3.amazonaws.com/images.ecwid.com/images/25838309/1444119673.jpg", title:"Muñeco Hedwig", precio:"$19.000", description:"La mascota interactiva de Harry Potter, responde a tu tacto y reconoce tu tono de voz. Hedwig gira su cabeza como, aleta sus alas y mueve su pico."}
];

export default Data;