const Data = [
    {id:1, category:{name:"otros", id:4}, img:"https://th.bing.com/th/id/R.fae30c371fdf03c8270b275fb83e6a2c?rik=HcjPRtk2qWUGyQ&pid=ImgRaw&r=0", title: "Pack libros Harry Potter", precio: "$17.000", stock: 2, description:'Incluye "La piedra filosofal", "La cámara secreta", "El pricionero de Azcaban", "El cáliz de fuego", "La orden del Fénix", "El misterio del príncipe" y "Las reliquias de la muerte"'},
    {id:2, category:{name:"Varitas", id:3}, img:"https://th.bing.com/th/id/OIP.pSL55k3_2sp2R_mSSmdCbgHaHa?pid=ImgDet&rs=1", title:"Varita Harry Potter", precio:"$5.000", stock: 16, description:'Varita Original de Ollivanders. La varita de Harry Potter mide veintiocho centímetros, y está hecha de acebo, con una pluma de fénix en su centro.'},
    {id:3, category:{name:"Casas", id:2}, img:"https://cuernavilla.com/12688/bufanda-ravenclaw-edicion-deluxe-harry-potter.jpg", title:"Bufanda de Ravenclaw", precio:"$4.000", stock: 22, description:'Bufanda de la casa Ravenclaw Original, con los colores azul y brince que caracteriza la casa. Empaque de Harri Potter Original, con etiqueta y escudo del aguila de Ravenclaw.'},
    {id:4, category:{name:"Muñecos", id:1}, img:"https://www.funkotienda.com/wp-content/uploads/2018/04/funko-pop-harry-potter-albus-dumbledore.jpg", title:"Funko Dumbledore", precio:"$8.850", stock: 8, description:'Figura coleccionable Funko Pop de Albus Dumbledore de la película "Harry Potter y la orden del fénix. Caja original. 10cm de altura"'},
    {id:5, category:{name:"otros", id:4}, img:"https://i.pinimg.com/originals/a3/b9/9f/a3b99fdedfcc2fbcf5b18b6acc165797.jpg", title:"Grageas de todos los sabores", precio:"$1.600", stock: 32, description:"Dulces mágicos de todos los sabores. Incluye: banana, huevo podrido, limón, vómito y más."},
    {id:6, category:{name:"Muñecos", id:1}, img:"https://media.entertainmentearth.com/assets/images/93d5a514ef9e44f09add18e7595fcc5dlg.jpg", title:"Sombrero seleccionador", precio:"$24.800", stock: 5, description:"Juguete interactivo del Sombrero seleccionador con voz incluida.Se coloca en la cabeza y mueve su boca para anunciar a qué casa de Hogwarts perteneces."},
    {id:7, category:{name:"otros", id:4}, img:"https://www.for-sale.co.uk/sh-img/91rOTxaOA3L._SL1500__chocolate%2Bfrog.jpg", title:"Rana de chocolate", precio:"$1.600", stock: 41, description:"Tras ranas de chocolate má una figura coleccionable con movimiento de los personajes de Harry Potter. No esperarás que se quede ahí todo el tiempo ¿o sí?"},
    {id:8, category:{name:"Muñecos", id:1}, img:"https://s3.amazonaws.com/images.ecwid.com/images/25838309/1444119673.jpg", title:"Muñeco Hedwig", precio:"$19.000", stock: 6, description:"La mascota interactiva de Harry Potter, responde a tu tacto y reconoce tu tono de voz. Hedwig gira su cabeza como, aleta sus alas y mueve su pico."},
    {id:9, category:{name:"Casas", id:2}, img:"https://cuernavilla.com/12686-superlarge_default/bufanda-slytherin-edicion-deluxe-harry-potter.jpg", title:"Bufanda de Slytherin", precio:"$4.000", stock: 45, description:'Bufanda de la casa Slytherin Original, con los colores verde y plateado que caracteriza a la casa. Empaque de Harri Potter Original, escudo de la serpiente de Slytherin.'},
    {id:10, category:{name:"Muñecos", id:1}, img:"https://bettoy.es/wp-content/uploads/2020/12/peluche-dobby-harry-potter-interactivo.jpg", title:"Muñeco Dobby", precio:"$14.000", stock: 2, description:'Muñeco del elfo doméstico, Dobby, parlante original de Hary Potter. Viene con un calcetín. Con 32cm de altura, dice las frases originales.'},
    {id:11, category:{name:"Varitas", id:3}, img:"https://http2.mlstatic.com/harry-potter-varita-de-sauco-dumbledore-lince-san-miguel-D_NQ_NP_531325-MPE25425888676_032017-F.jpg", title:"Varita de sauco", precio:"$5.000", stock: 12, description:'Varita de sauco original de Harry Potter. La varita de sauco fué hecha por la muerte en persona, lo que la hace la varita más poderosa.'},
    {id:12, category:{name:"Muñecos", id:1}, img:"https://fontan.io/media/www.warnerbros.fr/dc7f0f99.jpg", title:"Funko Ron", precio:"$8.850", stock: 19, description:'Figura coleccionable Funko Pop de Ron Weasley de la película "Harry Potter y el prisionero de Azcabán". Caja original. 10cm de altura'},
    {id:13, category:{name:"Casas", id:2}, img:"https://th.bing.com/th/id/OIP.kdKPZ7ydEwUQKpXHphBTbQHaHa?pid=ImgDet&rs=1", title:"Medias Gryffindor", precio:"$3.500", stock: 23, description:'Medias cortas originales de Harry Potter de la casa Gryffindor, con el escudo de el león y los colores rojo y dorado que representan a la casa'}
];

export default Data;